---

- name: get remote info
  setup:
  register: res

- name: only for Centos
  fail: msg="Sorry,the system is not support"
  when: res.ansible_facts.ansible_distribution != "CentOS"

- name: install openjdk
  yum: name=java-1.8.0-openjdk state=present

- name: add jenkins repo
  yum_repository:
    name: jenkins
    description: jenkins-stable
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    gpgcheck: 1

- name: install jenkins package
  yum: name=jenkins

- name: start jenkins
  service: name=jenkins state=started enabled=yes
