---

- name: download install script
  shell: php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');" chdir=$HOME

- name: run install script
  shell: php composer-setup.php chdir=$HOME

- name: copy to PATH
  shell: cp $HOME/composer.phar /usr/local/bin/composer

- name: set composer mirror
  shell: /usr/local/bin/composer config -g repo.packagist composer https://packagist.phpcomposer.com